- model_id: "t2i-adapter-canny"
  model: "TencentARC/T2I-Adapter"
  subfolder: "models"
  allow_patterns: "t2iadapter_canny_sd15v2.pth"
  type: "t2i_adapter"
  class: "T2iAdapter/from_state_dict(cin=64)"

- model_id: "t2i-adapter-color"
  model: "TencentARC/T2I-Adapter"
  subfolder: "models"
  allow_patterns: "t2iadapter_color_sd14v1.pth"
  type: "t2i_adapter"
  class: "T2iAdapter/from_state_dict(type=light)"

- model_id: "t2i-adapter-depth"
  model: "TencentARC/T2I-Adapter"
  subfolder: "models"
  allow_patterns: "t2iadapter_depth_sd15v2.pth"
  type: "t2i_adapter"
  class: "T2iAdapter/from_state_dict"

- model_id: "t2i-adapter-keypose"
  model: "TencentARC/T2I-Adapter"
  subfolder: "models"
  allow_patterns: "t2iadapter_keypose_sd14v1.pth"
  type: "t2i_adapter"
  class: "T2iAdapter/from_state_dict"

- model_id: "t2i-adapter-openpose"
  model: "TencentARC/T2I-Adapter"
  subfolder: "models"
  allow_patterns: "t2iadapter_openpose_sd14v1.pth"
  type: "t2i_adapter"
  class: "T2iAdapter/from_state_dict"

- model_id: "t2i-adapter-seg"
  model: "TencentARC/T2I-Adapter"
  subfolder: "models"
  allow_patterns: "t2iadapter_seg_sd14v1.pth"
  type: "t2i_adapter"
  class: "T2iAdapter/from_state_dict"

- model_id: "t2i-adapter-sketch"
  model: "TencentARC/T2I-Adapter"
  subfolder: "models"
  allow_patterns: "t2iadapter_sketch_sd15v2.pth"
  type: "t2i_adapter"
  class: "T2iAdapter/from_state_dict(cin=64,autoinvert=True)"

- model_id: "t2i-adapter-style"
  model: "TencentARC/T2I-Adapter"
  subfolder: "models"
  allow_patterns: "t2iadapter_style_sd14v1.pth"
  type: "t2i_adapter"
  class: "T2iAdapter/from_state_dict(type=style)"
  fp16: "prevent"
  overrides:
    clip: "@openai-clip-l"

- model_id: "t2i-adapter-zoedepth"
  model: "TencentARC/T2I-Adapter"
  subfolder: "models"
  allow_patterns: "t2iadapter_zoedepth_sd15v1.pth"
  type: "t2i_adapter"
  class: "T2iAdapter/from_state_dict"
